# This is a basic workflow to help you get started with Actions

name: Checkout

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
